name: moviescout
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytz
  - pip
  - pip:
    - python-dotenv
    - -e .
    - fastapi
    - uvicorn
    - transformers
    - torch
    - sentence-transformers
    - langchain
    - chromadb
    - pydantic
    - requests
    - tqdm